### ISSUE TITLE
data结构树

### ISSUE THREAD

**Issue by ifanshida** [DuZzzs/monodleX#3]
您好！我看了这两个问题，但还是没搞明白data结构该如何放置数据集。
我的目录如下：
#ROOT
|data/
----|KITTI/
------|training/
--------|ImageSets/
--------|calib/
--------|image_2/
--------|label/
------|testing/
--------|calib/
--------|image_2/

我修改了yaml文件中的root_dir位置为为\monodleX-main\data\KITTI，出现训练第一个echo时，还没开始训练时会报错如下：

File "../../tools/train_val.py", line 88, in
main()
File "../../tools/train_val.py", line 76, in main
trainer.train()
File "F:\xiangmu\monodleX-main\lib\helpers\trainer_helper.py", line 73, in train
self.train_one_epoch()
File "F:\xiangmu\monodleX-main\lib\helpers\trainer_helper.py", line 98, in train_one_epoch
for batch_idx, (inputs, targets, _) in enumerate(self.train_loader):
File "D:\Anaconda3\envs\monodle\lib\site-packages\torch\utils\data\dataloader.py", line 582, in next
return self._process_next_batch(batch)
File "D:\Anaconda3\envs\monodle\lib\site-packages\torch\utils\data\dataloader.py", line 608, in _process_next_batch
raise batch.exc_type(batch.exc_msg)
AssertionError: Traceback (most recent call last):
File "D:\Anaconda3\envs\monodle\lib\site-packages\torch\utils\data_utils\worker.py", line 99, in _worker_loop
samples = collate_fn([dataset[i] for i in batch_indices])
File "D:\Anaconda3\envs\monodle\lib\site-packages\torch\utils\data_utils\worker.py", line 99, in
samples = collate_fn([dataset[i] for i in batch_indices])
File "F:\xiangmu\monodleX-main\lib\datasets\kitti\kitti_dataset.py", line 157, in getitem
objects = self.get_label(index)
File "F:\xiangmu\monodleX-main\lib\datasets\kitti\kitti_dataset.py", line 86, in get_label
assert os.path.exists(label_file)
AssertionError

想请问大佬这还是我数据集放的位置不对的问题吗？看样子好像是无法正确读取标签，还是想问一下大佬data的结构树是什么样的

**Comment by DuZzzs** [comment]
@ifanshida 看着没问题，可能是多了一层或者少了一层。在kitti_dataset.py里看下

**Comment by ifanshida** [comment]
> @ifanshida 看着没问题，可能是多了一层或者少了一层。在kitti_dataset.py里看下

非常感谢！是文件夹名字的问题，改成kitti_dataset.py里文件夹名字就可以了
